services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  postgres_data:
  redis_data:
